API_URL = "https://traction-sandbox-tenant-proxy.apps.silver.devops.gov.bc.ca"
AUTH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3YWxsZXRfaWQiOiIyYzA4MDE0MC0yYzVkLTRkMTAtOWE0YS00NzUwZmU5YTc2ODkiLCJpYXQiOjE3MjkyMTU5MjYsImV4cCI6MTcyOTMwMjMyNn0.KVyPOdwbFVbk31qhywHPSc-h8eE4HZBx_r6KlzujzVo"
